### ISSUE TITLE
Letter semantics

### ISSUE THREAD

**Issue by acabal** [scriptdaemon/j-sheridan-le-fanu_uncle-silas#1]
I'm looking at `chapter-2-25.xhtml` and there's a letter that seems fairly problematic:

- The `<blockquote>` element has `epub:type="z3998:place"`, which doesn't make sense; it should be `z3998:letter`
- It looks like you used the unsemantic `i2`, `i3`, and `right` classes to style indented text. Instead of doing that, please find appropriate semantics that describe the meaning of the elements you want to style, and then target them for styling using those semantics. In other words, we should never add classes that describe the style you want; instead, add classes or `epub:type` attributes that describe what the element *is*, then style *that*. (The exception is `i1`, `i2`, etc. when used in *verse* per our manual--but *only* for verse.)

I don't think this occurs in other letters but please review any other ones to make sure they follow that thinking.

**Comment by scriptdaemon** [comment]
At least several of them use those semantics. I used those because not all letters in the text are styled the same way, so styling them just based on e.g. letter > salutation is tricky and conflicts with other letters that aren't written the same way in the source text. I'll revisit this however and see what I can figure out.

**Comment by scriptdaemon** [comment]
I believe I have addressed this issue in the most recent commit. The letter referenced in your original issue no longer replicates the styling from the source text exactly (it's styled differently from all other letters in the text, so there was no way to manage it the way I had it before without extra classes), but I'm not sure how important that is. Unless there are other issues you find, this should now be good to go.
