### ISSUE TITLE
Spelling inconsistencies?

### ISSUE THREAD

**Issue by acabal** [scriptdaemon/j-sheridan-le-fanu_uncle-silas#2]
In the production notes, it says spelling inconsistencies are retained. But, that is certainly something we generally would prefer to correct. What inconsistencies are you referring to, and why did you decide to keep them instead of correct them?

**Comment by scriptdaemon** [comment]
Those were the transcriber's notes from the Gutenberg release, and I *think* it's referring to the quoted text within the book (when speaking, sometimes e.g. someone will say the whole word and other times will abbreviate it). Should we not consider this as abnormal and thus not require production notes regarding them?

**Comment by acabal** [comment]
Ah. The production-notes section is for *your* production notes, not the PG transcriber.

If the abbreviation is in dialog then we should keep it since that's how a person is speaking. When I see "spelling inconsistences" I think: one instance of "Ruthyn" and one instance of "Ruthin" for example. In the past it was common for printers and publishers to have to re-set printing plates for new editions and that's one of the many places that these kinds of inconsistencies would be introduced, which we are interested in correcting.
